[package]
name = "aws-ip-provisioner"
version = "0.0.7" # https://github.com/gyuho/ip-manager/releases
edition = "2021"
rust-version = "1.65"
description = "AWS IP provisioner"
repository = "https://github.com/gyuho/ip-manager"
readme = "README.md"
license = "Apache-2.0"

[[bin]]
name = "aws-ip-provisioner"
path = "src/main.rs"

[dependencies]
aws-manager = "0.22.0" # https://crates.io/crates/aws-manager/versions
aws-sdk-ec2 = "0.22.0"
chrono = "0.4.23"
clap = { version = "4.0.29", features = ["cargo", "derive"] }
command-manager = "0.0.1"
env_logger = "0.10.0"
log = "0.4.17"
path-clean = { version = "0.1.0", optional = false }
random-manager = "0.0.1"
tokio = { version = "1.23.0", features = ["full"] }
walkdir = { version = "2.3.2", optional = false }
