[package]
name = "aws-ip-provisioner"
version = "0.0.16" # https://github.com/gyuho/ip-manager/releases
edition = "2021"
rust-version = "1.66"
description = "AWS IP provisioner"
repository = "https://github.com/gyuho/ip-manager"
readme = "README.md"
license = "Apache-2.0"

[[bin]]
name = "aws-ip-provisioner"
path = "src/main.rs"

[dependencies]
aws-manager = {version = "0.22.17", features = ["ec2"] } # https://crates.io/crates/aws-manager
aws-sdk-ec2 = "0.22.0"
clap = { version = "4.0.32", features = ["cargo", "derive"] }
env_logger = "0.10.0"
log = "0.4.17"
random-manager = "0.0.2"
tokio = { version = "1.23.0", features = ["full"] }
